language: rust

rust:
  - stable
  - beta
  - nightly

sudo: false

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

install: pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

addons:
  apt:
    packages:
      - postfix

before_script:
  - smtp-sink 2525 1000&

script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo doc
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench; fi'

after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo --only stable coveralls

env:
  global:
    secure: "MaZ3TzuaAHuxmxQkfJdqRfkh7/ieScJRk0T/2yjysZhDMTYyRmp5wh/zkfW1ADuG0uc4Pqsxrsh1J9SVO7O0U5NJA8NKZi/pgiL+FHh0g4YtlHxy2xmFNB5am3Kyc+E7B4XylwTbA9S8ublVM0nvX7yX/a5fbwEUInVk2bA8fpc="
