language: rust
rust:
- stable
- beta
- nightly
sudo: false
cache:
  apt: true
  pip: true
  directories:
  - target/debug/deps
  - target/debug/build
  - target/release/deps
  - target/release/build
install:
- pip install 'travis-cargo<0.2' --user
- pip install 'ghp-import' --user
- export PATH=$HOME/.local/bin:$PATH
addons:
  apt:
    packages:
    - postfix
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
before_script:
- smtp-sink 2525 1000&
script:
- travis-cargo build
- travis-cargo test
after_success: |
  travis-cargo --only nightly bench &&
  travis-cargo --only stable coveralls --no-sudo &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  cargo doc --no-deps &&
  cd target/doc && git init &&
  git push -fq https://${TOKEN}@github.com/lettre/lettre.github.io.git master
env:
  global:
    secure: sCYtnA/nHhOye43NuxI0VAL8+hf/60nxwfBBCKOsA+0P/U5dDlLoTiW+zcn5ejxBuQbM6GIUuaLe35UqWy5krZda6jpTTtSZNC6Hw5b7UgT8wJ8NN8EuiOsecph019XuTyDLEO7z9vKg/fEgktKbSwnfSlyBMDfgOhwJDfpgwLokbOcFz/zUyCX+b1hHo0EGS0OpDcB9FNX8veYVoz8NET26dvHfws+ZxJAawaUaL72A2L30I9eHe+kc2w8vLJp7wIUM24tXO2gn/sZikMuAuiwhkT76S/pPMl6K2bw/WlrVK9HsgXtM76PlsylNwHZDdUQTDD5Vwfi4K/D73+DkWR5hW0MfcG+wSzDbAXmPbiSVoOmwpuMXnNf6xuMXfZeVDLbBqqjwc760YrOSpsfbVd84JTk17q61eqRuNr5bv/gM7qRydzPJjCr+SJ6Y1Qny+Saepdl6OERfhfrwwGNBlF8xlwQFpIr068LLncl0QxryfIRAhXuseD+mNmhU4MEsPl4mgJdEelVV4E4oMsPtDHaNqEtT6DrYMuVE9sFkvv/4va6cl+1ZRrJVF3/TGpFalLLdq3VCaHI6cadJuRb+VMvsvoZ5WZKCk6j3AIIPp7m7o4flUiHesnkgaPcet3D+Ii6V1ipkvKanzAweh74Faghylr2xYAXfetUbtKKTF+c=
