language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y postfix
  - sudo netstat -taupe
  - cat /etc/postfix/{main.cf,master.cf}
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo build &&
      travis-cargo test
  -   export RUST_LOG=debug
  -   ./target/debug/examples/client
  -   travis-cargo doc
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo --only stable coveralls

env:
  global:
    secure: "MaZ3TzuaAHuxmxQkfJdqRfkh7/ieScJRk0T/2yjysZhDMTYyRmp5wh/zkfW1ADuG0uc4Pqsxrsh1J9SVO7O0U5NJA8NKZi/pgiL+FHh0g4YtlHxy2xmFNB5am3Kyc+E7B4XylwTbA9S8ublVM0nvX7yX/a5fbwEUInVk2bA8fpc="
