language: rust

rust:
  - stable
  - beta
  - nightly

sudo: false

cache:
    apt: true
    pip: true
    directories:
        - target/debug/deps
        - target/debug/build
        - target/release/deps
        - target/release/build

install:
  - pip install 'travis-cargo<0.2' --user
  - pip install 'ghp-import' --user
  - export PATH=$HOME/.local/bin:$PATH

addons:
  apt:
    packages:
      - postfix
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

before_script:
  - smtp-sink 2525 1000&

script:
  - travis-cargo build
  - travis-cargo test

after_success: |
  travis-cargo --only nightly bench &&
  travis-cargo --only stable coveralls --no-sudo &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  cargo doc --no-deps &&
  ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/lettre/lettre.github.io.git master

env:
  global:
    secure: "MaZ3TzuaAHuxmxQkfJdqRfkh7/ieScJRk0T/2yjysZhDMTYyRmp5wh/zkfW1ADuG0uc4Pqsxrsh1J9SVO7O0U5NJA8NKZi/pgiL+FHh0g4YtlHxy2xmFNB5am3Kyc+E7B4XylwTbA9S8ublVM0nvX7yX/a5fbwEUInVk2bA8fpc="
