[package]

name = "smtp"
version = "0.4.0"
description = "Simple SMTP client"
readme = "README.md"
documentation = "http://amousset.me/rust-smtp/smtp/"
repository = "https://github.com/amousset/rust-smtp"
license = "MIT"
authors = ["Alexis Mousset <alexis.mousset@gmx.fr>"]
keywords = ["email", "smtp", "mailer"]

[dependencies]
time = "0.1"
uuid = "0.1"
log = "0.3"
rustc-serialize = "0.3"
rust-crypto = "0.2"
bufstream = "0.1"
email = "0.0"
openssl = "0.6"

[dev-dependencies]
env_logger = "0.3"

[features]
unstable = []
