name: Website

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cargo install mdbook mdbook-linkcheck
    - run: cd website && mdbook build
    - run: echo "lettre.at" > website/_book/html/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_PAT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./website/_book
